zomboid = simpleGameEngine('retro_pack.png',16,16,5)

% 
% runLevel(zomboid,'roadCompChoice.txt')
% pause(.5)
% runLevel(zomboid,'roadComp1.txt')
% pause(.5)
% runLevel(zomboid,'roadComp2.txt')
% pause(.5)
% runLevel(zomboid,'building1Comp.txt')
% pause(.5)
% runLevel(zomboid,'building2Comp.txt')
% pause(.5)
% runLevel(zomboid,'building3Comp.txt')
% pause(.5)
% runLevel(zomboid,'building4Comp.txt')
% pause(.5)
% runLevel(zomboid,'building5Comp.txt')
 

runLevel(zomboid,'roadChoice.txt')
pause(.5)
runLevel(zomboid,'road1.txt')
pause(.5)
runLevel(zomboid,'road2.txt')
pause(.5)
runLevel(zomboid,'building1.txt')
pause(.5)
runLevel(zomboid,'building2.txt')
pause(.5)
runLevel(zomboid,'building3.txt')
pause(.5)
runLevel(zomboid,'building4.txt')
pause(.5)
runLevel(zomboid,'building5.txt')